### ISSUE TITLE
Cannot find sentry on php artisan db:seed

### ISSUE THREAD

**Issue by necrogami** [bstrahija/l4-site-tutorial#1]
`$ php artisan db:seed
PHP Fatal error:  Class 'Sentry' not found in /Users/aswartz/githosting/tools/app/database/seeds/SentrySeeder.php on line 14
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Sentry' not found","file":"\/Users\/aswartz\/githosting\/tools\/app\/database\/seeds\/SentrySeeder.php","line":14}}`

If i add `use Cartalyst\Sentry\Sentry;` i get:

`$ php artisan db:seed
{"error":{"type":"ErrorException","message":"Non-static method Cartalyst\\Sentry\\Sentry::getUserProvider() should not be called statically, assuming $this from incompatible context","file":"\/Users\/aswartz\/githosting\/tools\/app\/database\/seeds\/SentrySeeder.php","line":14}}`

**Comment by necrogami** [comment]
This can be closed. i found the bug.

In your part one of the tutorial you forgot to add:

`'Cartalyst\Sentry\SentryServiceProvider',` to app/config/app.php under providers and 
`'Sentry'          => 'Cartalyst\Sentry\Facades\Laravel\Sentry',` to app/config/app.php under aliases

**Comment by bstrahija** [comment]
As I noted in the tutorial comments, I didn't forget anything ;) It says:

To complete installation for the Sentry package consult the Sentry docs: http://docs.cartalyst.com/sentry-2/installation/laravel-4
