### ISSUE TITLE
Pagination link buttons not showing

### ISSUE THREAD

**Issue by teodorsandu** [bstrahija/l4-site-tutorial#12]
I tried to paginate, but the buttons with links (prev, 2,3,4,next) doesn't show up
In public/site/routes.php:
Route::get('blog', array('as' => 'article.list', function()
{
    return View::make('site::articles')->with('entries', Article::orderBy('created_at'  , 'DESC')/*)->get() */->paginate(2));
}));

If I type
/public/blog?page=1,2,3 etc
it diplays the two articles of the page correctly, but without the buttons.

**Comment by bstrahija** [comment]
Where are you trying to render the pagination, in which view?

Did you follow the docs? http://laravel.com/docs/pagination

**Comment by teodorsandu** [comment]
( I try to render the pagination in public/site/views/articles.blade.php. )

Wow, my fault -  I forgot <?php echo $entries->links(); ?> :D

@include('site::_partials/header')

<h2>Articles</h2>

<hr>

<ul class="articles">
    [...cutted...]
</ul>

<?php echo $entries->links(); ?>

@include('site::_partials/footer')

 The bootstrap.min.css and bootstrap.min.js are loaded correctly.

Thank you for your website and for your tutorial, they are help me a lot, and sorry for opening a false issue. :hand:
