### ISSUE TITLE
$entry->author->email?

### ISSUE THREAD

**Issue by jeremyvaught** [bstrahija/l4-site-tutorial#2]
I'm following along in your (so far 3 part) tutorial. Although $entry->author->email in the article and articles view is giving me an error of "Trying to get property of non-object".

Have I gone wrong somewhere?

Thanks for the tutorial by the way. VERY helpful.

**Comment by bstrahija** [comment]
Have you defined the relation in your article model:

```
public function author()
{
    return $this->belongsTo('App\Models\User', 'user_id');
}
```

If you have, try var_dumping $entry->author. Do you have a related user for the article?

**Comment by jeremyvaught** [comment]
Ahhh, that was it. When you said 'related user' I knew what the problem was. In the article table, it was looking for user 1, but the admin user was higher than. 

And I was also a bit confused because there is no 'author' in the database, but see now it comes from that function in the model.

Sorry to bother you, but MUCH appreciated. Thanks again for this tutorial, and thank you as well for your response!

**Comment by bstrahija** [comment]
Glad you like the tutorial ;)
