### ISSUE TITLE
ContentSeeder.php issue

### ISSUE THREAD

**Issue by seandelaney** [bstrahija/l4-site-tutorial#5]
Hi,

Just started following your tutorial over here:

I'm as far as creating the ContentSeeder.php class and running 'php artisan db:seed'.

However I get the following issue in the console:

<pre><code>Sentry tables seeded!
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'App\\Models\\Article' not found","file":"\/Users\/seandelaney\/Sites\/laravel-development.local\/app\/database\/seeds\/ContentSeeder.php","line":17}}</code></pre>

I've used the same contents as your ContentSeeder.php file:

<pre>use App\Models\Article;
use App\Models\Page;
 
class ContentSeeder extends Seeder {
    public function run() {
        DB::table('articles')->delete();
        DB::table('pages')->delete();
 
        Article::create(array(
            'title'   => 'First post',
            'slug'    => 'first-post',
            'body'    => 'Lorem ipsum dolor sit amet...',
            'user_id' => 1,
        ));
        
        Page::create(array(
            'title'   => 'About us',
            'slug'    => 'about-us',
            'body'    => 'Lorem ipsum dolor sit amet...',
            'user_id' => 1,
        ));
    }
}</pre>

Any ideas ?

**Comment by bstrahija** [comment]
Did you run "composer dump-autoload" after creating the classes?

**Comment by seandelaney** [comment]
No. That command is not mentioned in the tutorial?

(http://www.codeforest.net/laravel4-simple-website-with-backend-1)

I'll run that command and re-run 'php artisan db:seed' again.

**Comment by bstrahija** [comment]
But it's mentioned that you should basic composer stuff before jumping into the tutorial ;)

**Comment by yethusoe91** [comment]
hello, i faced the same error , how can i solve pls?

**Comment by bstrahija** [comment]
Did you run "composer dump"?
