### ISSUE TITLE
Fresh install - ErrorException: Trying to get property of non-object

### ISSUE THREAD

**Issue by ghost** [bstrahija/l4-site-tutorial#9]
After a fresh install it doesn't work using 0.4.0. Neither dev-master

**Comment by bstrahija** [comment]
The problem is that you didn't sees the database.
I updated the "app:install" command so it now also seeds the DB. Just clone the repo, run "composer install" and "artisan app:install" and you're good to go.

**Comment by odyright** [comment]
artisan app:install doesnt work for me!

**Comment by odyright** [comment]
ok i solved it ....it is "php artisan app:install" instead that above...! good job Boris Strahija
